import { filterDateParams, currencyFormatter, signFormatter, roundOffDecimal } from '../../../services/common_services';

export const columns = [
    {        
        headerName: 'ID',
        minWidth: 100,
        maxWidth: 100,
        valueGetter: "node.id",
        cellRenderer: 'loadingRenderer'
    },
    {
        field: 'fundName',
        headerName: 'Fund Name',
        minWidth: 150,
        flex: 1,
        filter: 'agSetColumnFilter',
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true
    },
    {
        field: 'dataAsOfQuarter',
        headerName: 'Data as of Quarter',
        filter: 'agSetColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true
    },
    {
        field: 'grossIRR',
        headerName: 'Gross IRR',
        valueFormatter: params => signFormatter(params?.data?.grossIRR, '%'),
        filter: 'agNumberColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'netIRR',
        headerName: 'Net IRR',
        valueFormatter: params => signFormatter(params?.data?.netIRR, '%'),
        filter: 'agNumberColumnFilter',
        width: 100,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'grossMOIC',
        headerName: 'Gross MOIC',
        valueFormatter: params => roundOffDecimal(params?.data?.grossMOIC),
        filter: 'agNumberColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'netMOIC',
        headerName: 'Net MOIC',
        valueFormatter: params => roundOffDecimal(params?.data?.netMOIC),
        filter: 'agNumberColumnFilter',
        width: 100,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'NAV',
        headerName: 'NAV',
        valueFormatter: params => currencyFormatter(params?.data?.NAV, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'distributionsCapitalDPI',
        headerName: 'DPI',
        valueFormatter: params => roundOffDecimal(params?.data?.distributionsCapitalDPI),
        filter: 'agNumberColumnFilter',
        width: 150,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'TVPI',
        headerName: 'TVPI',
        valueFormatter: params => roundOffDecimal(params?.data?.TVPI),
        filter: 'agNumberColumnFilter',
        width: 100,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'RVPI',
        headerName: 'RVPI',
        valueFormatter: params => roundOffDecimal(params?.data?.RVPI),
        filter: 'agNumberColumnFilter',
        width: 100,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'PiCC',
        headerName: 'PiCC',
        valueFormatter: params => roundOffDecimal(params?.data?.PiCC),
        filter: 'agNumberColumnFilter',
        width: 100,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open'
    },
    {
        field: 'totalCommitments',
        headerName: 'Commited Capital',
        valueFormatter: params => currencyFormatter(params?.data?.totalCommitments, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 150,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'calledCapital',
        headerName: 'Called Capital',
        valueFormatter: params => currencyFormatter(params?.data?.calledCapital, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'undrawnCapital',
        headerName: 'Undrawn Capital',
        valueFormatter: params => currencyFormatter(params?.data?.undrawnCapital, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'distributedCapital',
        headerName: 'Distributed Capital',
        valueFormatter: params => currencyFormatter(params?.data?.distributedCapital, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 150,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'recallableCapital',
        headerName: 'Recallable Capita',
        valueFormatter: params => currencyFormatter(params?.data?.recallableCapital, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 150,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'totalInvestedPortfolioCompanies',
        headerName: 'Total invested in Portfolio Companies',
        valueFormatter: params => currencyFormatter(params?.data?.totalInvestedPortfolioCompanies, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 170,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'totalPortfolioFairValue',
        headerName: 'Total Fair Value of Portfolio',
        valueFormatter: params => currencyFormatter(params?.data?.totalPortfolioFairValue, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 170,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'totalAdditionalCapital',
        headerName: 'Total Additional Portfolio',
        valueFormatter: params => currencyFormatter(params?.data?.totalAdditionalCapital, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 170,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'carryPaid',
        headerName: 'Carry Paid',
        valueFormatter: params => currencyFormatter(params?.data?.carryPaid, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'managementFeePaid',
        headerName: 'Management Fee',
        valueFormatter: params => currencyFormatter(params?.data?.managementFeePaid, params?.data?.fundCurrency),
        filter: 'agNumberColumnFilter',
        width: 150,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    },
    {
        field: 'dataAsOf',
        headerName: 'Data As Of',
        filter: 'agDateColumnFilter',
        filterParams: { filterDateParams },
        width: 120,
        flex: 0,
        enablePivot: true,
        enableRowGroup: true,
        enableValue: true,
        columnGroupShow: 'open',
        hide: true
    }
];