// export const BASEURL = checkProd() ? CONFIG.PRODUCTION_API_HOST : CONFIG.DEVELOPMENT_API_HOST
// export const HOSTURL = 'https://us-central1-aztec-data-dev.cloudfunctions.net/'
export const RESTAPI = {
    GET_USER_DATA: 'user_ops/get_data',
    SET_USER_DATA: 'user_ops/set_data',
    UPDATE_PROFILE: 'user_ops/update_profile',
    UPLOAD_IMAGE: 'user_ops/update_profile_picture',
    GET_ORGANISATION_DATA: 'organisation_ops/get_data',
    GET_HOME_DATA: 'organisation_ops/get_home_data',
    GET_USERS: 'user_ops/get_all',
    SAVE_USER_PERMISSIONS: 'user_ops/save_permissions',
    GET_REPORTS: 'report_ops/get_data',
    GET_RECOMENDATION: 'recommendations',
    GET_RECOMMENDATION_PREVIEW: 'rec_preview/preview',
    GET_RECOMENDATION_SUMMARY: 'rec_summary',
    GET_COMPANY_DETAILS: 'all',
    GET_COMPANY_DETAILS_OVERVIEW: 'overview',
    GET_COMPANY_DETAILS_ABOUT: 'about',
    GET_COMPANY_DETAILS_PEOPLE_IMAGE: 'people_images',
    GET_COMPANY_DETAILS_SIMILAR_COMPANIES: 'similar',
    GET_COMPANY_DETAILS_STATISTICS: 'statistics',
    GET_COMPANY_DETAILS_INVESTMENTS: 'investments',
    GET_COMPANY_DETAILS_GROWTH: 'growth',
    GET_COMPANY_DETAILS_SUMMARY: 'summary',
    SEARCH_COMPANY: 'autocomplete',
    GET_MARKET_COMPANY: 'forecast_trends_entities/get_market_factor',
    GET_COMPANY_PERFORMANCE: 'forecast_trends_entities/get_company_performance',
    GET_MACRO_TRENDS: 'autocomplete/get_macro_trends',
    GET_ENTITIES: 'autocomplete/get_entities',
    GET_BENCHMARK_DATA: 'benchmark_ops/get_data',
    ADD_BENCHMARK_DATA: 'benchmark_ops/add',
    DELETE_BENCHMARK_DATA: 'benchmark_ops/delete',
    ADD_KPI_DATA: 'organisation_ops/add_box',
    GET_BENCHMARK_KPI: 'benchmark_ops/boxes',
    GET_BENCHMARK_CHART: 'benchmark_ops/chart',
    GET_BENCHMARK_CREATE_DATA: 'benchmark_ops/external_funds',
    GET_BENCHMARK_TABLE: 'benchmark_ops/table',
    ADD_BENCHMARK_TABLE: 'benchmark_ops/add_benchmark_data',
    KEYLINE: 'keylines',
    PREDICT_TREND_ENTITIES: 'predict_trends_entities',
    GET_FUND_GRAPH: 'autocomplete/get_fund_graph',
    COMAPNY_DETAILS: 'company_details',
    GET_CONFIG: 'config/get_config',
    GET_GP_DETAILS: 'organisation_ops/get_gp_details',
    VERIFY_USER: 'user_ops/verify_user'
}
